### ISSUE TITLE
Internal server Error

### ISSUE THREAD

**Issue by gamersindo1223** [unixfox/pupflare#35]
Just trying this repo on my GH codespaces,
But got this error
```
TypeError: Cannot convert undefined or null to object
      at /workspaces/pupflare/index.js:107:78
      at Array.forEach (<anonymous>)
      at /workspaces/pupflare/index.js:107:37
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async bodyParser (/workspaces/pupflare/node_modules/koa-bodyparser/index.js:78:5)
```
 Website that I used for this request is https://example.com

**Comment by unixfox** [comment]
no idea, it runs fine in local. I don't have time to investigate why it doesn't work on github codespace.
